server:
  port: 8090

spring:
  application:
    name: pay

  datasource:
    type: com.zaxxer.hikari.HikariDataSource      # 默认，可不写
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment_demo?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 789456      # 如果是0开头,加上单引号不然可能会报错

  # 指定返回给前端的日期数据格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis-plus
mybatis-plus:
  # type-aliases-package: com.atguigu.model.system
  configuration:
    # 当执行sql时，会在控制台输出日志信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full    #开启自动映射 利于多表查询,resultMap的result标签可以不写
  global-config:
    db-config:
      id-type: auto #主键策略自增长,不写默认雪花,接值需要用Long或String,数据库用的是bigint或varchar(64)
      update-strategy: not_empty  # 在更新时只更新非空和非null的字段

#logging:
#  level:
#    root: debug
